apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-connection-drain: "on"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-connection-drain-timeout: "240"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-instance-charge-type: paybytraffic
  finalizers:
  - service.k8s.alibaba/resources
  labels:
    app: nginx-ingress-lb
  name: nginx-ingress-lb
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - name: http
    nodePort: 30128
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
