# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

alias ls='ls -G'

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export JAVA_HOME=`/usr/libexec/java_home`
export PATH=$JAVA_HOME/bin:$PATH

unset M2_HOME

