# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color'

HISTTIMEFORMAT="%Y%m%d-%H%M%S: "
export HISTTIMEFORMAT

export JAVA_HOME=/usr/java/default
export M2_HOME=/opt/apache-maven-3.3.3
export GOPATH=/vagrant/gopath

export PATH=$PATH:$M2_HOME/bin
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

source ~/.git-completion.bash
