# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias rm='rm -i'
alias ls='ls --color'
alias ll='ls -l'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color'
alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'

HISTTIMEFORMAT="%Y%m%d-%H%M%S: "
export HISTTIMEFORMAT

export JAVA_HOME=/usr/java/default
export M2_HOME=/opt/apache-maven-3.3.3
export SCALA_HOME=/opt/scala
export GOPATH=/vagrant/gopath
export NODEPATH=/vagrant/gopath

export PATH=$JAVA_HOME/bin:$PATH
export PATH=$PATH:$M2_HOME/bin
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export PATH=$PATH:$SCALA_HOME/bin

source ~/.git-completion.bash

export LANG=en_US.UTF-8
