"set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'The-NERD-tree'
Plugin 'sickill/vim-monokai'

Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-fugitive'

"Plugin 'vim-airline/vim-airline'
"Plugin 'vim-airline/vim-airline-themes'

Plugin 'pangloss/vim-javascript'
Plugin 'moll/vim-node'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'derekwyatt/vim-scala'
Plugin 'spacewander/openresty-vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'udalov/kotlin-vim'
"Plugin 'fatih/vim-go'
Plugin 'stephpy/vim-yaml'
Plugin 'robbles/logstash.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" airline
" set laststatus=2
"let g:airline_theme='molokai'
"let g:airline_powerline_fonts = 1
"if !exists('g:airline_symbols')
"    let g:airline_symbols = {}
"endif
"let g:airline_symbols.space = "\ua0"

syntax on
"set background=dark
colorscheme desert
"colorscheme monokai

"let g:solarized_bold=0
"let g:solarized_contrast="low"
"let g:solarized_termcolors=256
"colorscheme solarized

set t_Co=256
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set autoindent
set number
set ruler
set hlsearch
set smartindent
set encoding=utf-8
set pastetoggle=<F9>
let NERDTreeDirArrows=0 
"au BufNewFile,BufRead *.json set filetype=javascript

let g:vim_markdown_folding_disabled=1

source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
set backspace=indent,eol,start

au BufRead,BufNewFile /etc/nginx/*,*/conf/nginx.conf,*/nginx/conf.d/*.conf,*/conf/vhosts/*.conf,*/conf.d/*.conf setfiletype nginx
"au BufRead,BufNewFile /etc/nginx/*,*/conf/nginx.conf,*/nginx/conf.d/*.conf if &ft == '' | setfiletype nginx | endif
"
